### ISSUE TITLE
Send for Shaders?

### ISSUE THREAD

**Issue by grampelberg** [junkdog/tachyonfx#8]
I'm using Tokio for my event/render loop and would love to be able to `Send`. It looks like there's `Rc<RefCell<T>>` so that might not be worth the effort, I'm not sure I understand all the implications.

Note: `tokio::task::spawn_local` gets rid of the `Send` requirement.

For some added details, I'm working on a custom SSH server that draws a dashboard per-connection, so I do a `tokio::spawn` for the event/render loop on each connection.

**Comment by junkdog** [comment]
I think I'll need to experiment a bit with async ratatui. I presume `Send` is sufficient or is `Sync` also required?

**Comment by grampelberg** [comment]
Send is all that is required for my use case, luckily.

**Comment by junkdog** [comment]
It's WIP, but have a look at the [sendable-effects](https://github.com/junkdog/tachyonfx/tree/sendable-effects) branch and see if looks/works ok.

It all or nothing, feature-gated behind "sendable".  I'm not sure it's the best approach, but it was the least invasive option.

**Comment by junkdog** [comment]
merged to development
